package br.com.supera.smartiot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResourceGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceGroupAllPropertiesEquals(ResourceGroup expected, ResourceGroup actual) {
        assertResourceGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertResourceGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceGroupAllUpdatablePropertiesEquals(ResourceGroup expected, ResourceGroup actual) {
        assertResourceGroupUpdatableFieldsEquals(expected, actual);
        assertResourceGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceGroupAutoGeneratedPropertiesEquals(ResourceGroup expected, ResourceGroup actual) {
        assertThat(expected)
            .as("Verify ResourceGroup auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceGroupUpdatableFieldsEquals(ResourceGroup expected, ResourceGroup actual) {
        assertThat(expected)
            .as("Verify ResourceGroup relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceGroupUpdatableRelationshipsEquals(ResourceGroup expected, ResourceGroup actual) {}
}
