package br.com.supera.smartiot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserRoleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserRoleAllPropertiesEquals(UserRole expected, UserRole actual) {
        assertUserRoleAutoGeneratedPropertiesEquals(expected, actual);
        assertUserRoleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserRoleAllUpdatablePropertiesEquals(UserRole expected, UserRole actual) {
        assertUserRoleUpdatableFieldsEquals(expected, actual);
        assertUserRoleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserRoleAutoGeneratedPropertiesEquals(UserRole expected, UserRole actual) {
        assertThat(expected)
            .as("Verify UserRole auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserRoleUpdatableFieldsEquals(UserRole expected, UserRole actual) {
        assertThat(expected)
            .as("Verify UserRole relevant properties")
            .satisfies(e -> assertThat(e.getRoleName()).as("check roleName").isEqualTo(actual.getRoleName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserRoleUpdatableRelationshipsEquals(UserRole expected, UserRole actual) {}
}
