package br.com.supera.smartiot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VehicleGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleGroupAllPropertiesEquals(VehicleGroup expected, VehicleGroup actual) {
        assertVehicleGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertVehicleGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleGroupAllUpdatablePropertiesEquals(VehicleGroup expected, VehicleGroup actual) {
        assertVehicleGroupUpdatableFieldsEquals(expected, actual);
        assertVehicleGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleGroupAutoGeneratedPropertiesEquals(VehicleGroup expected, VehicleGroup actual) {
        assertThat(expected)
            .as("Verify VehicleGroup auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleGroupUpdatableFieldsEquals(VehicleGroup expected, VehicleGroup actual) {
        assertThat(expected)
            .as("Verify VehicleGroup relevant properties")
            .satisfies(e -> assertThat(e.getGroupName()).as("check groupName").isEqualTo(actual.getGroupName()))
            .satisfies(e -> assertThat(e.getGroupDescription()).as("check groupDescription").isEqualTo(actual.getGroupDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleGroupUpdatableRelationshipsEquals(VehicleGroup expected, VehicleGroup actual) {}
}
