package br.com.supera.smartiot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VehicleModelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleModelAllPropertiesEquals(VehicleModel expected, VehicleModel actual) {
        assertVehicleModelAutoGeneratedPropertiesEquals(expected, actual);
        assertVehicleModelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleModelAllUpdatablePropertiesEquals(VehicleModel expected, VehicleModel actual) {
        assertVehicleModelUpdatableFieldsEquals(expected, actual);
        assertVehicleModelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleModelAutoGeneratedPropertiesEquals(VehicleModel expected, VehicleModel actual) {
        assertThat(expected)
            .as("Verify VehicleModel auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleModelUpdatableFieldsEquals(VehicleModel expected, VehicleModel actual) {
        assertThat(expected)
            .as("Verify VehicleModel relevant properties")
            .satisfies(e -> assertThat(e.getModelName()).as("check modelName").isEqualTo(actual.getModelName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleModelUpdatableRelationshipsEquals(VehicleModel expected, VehicleModel actual) {}
}
