package br.com.supera.smartiot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VehicleSubStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleSubStatusAllPropertiesEquals(VehicleSubStatus expected, VehicleSubStatus actual) {
        assertVehicleSubStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertVehicleSubStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleSubStatusAllUpdatablePropertiesEquals(VehicleSubStatus expected, VehicleSubStatus actual) {
        assertVehicleSubStatusUpdatableFieldsEquals(expected, actual);
        assertVehicleSubStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleSubStatusAutoGeneratedPropertiesEquals(VehicleSubStatus expected, VehicleSubStatus actual) {
        assertThat(expected)
            .as("Verify VehicleSubStatus auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleSubStatusUpdatableFieldsEquals(VehicleSubStatus expected, VehicleSubStatus actual) {
        assertThat(expected)
            .as("Verify VehicleSubStatus relevant properties")
            .satisfies(e -> assertThat(e.getSubStatusName()).as("check subStatusName").isEqualTo(actual.getSubStatusName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleSubStatusUpdatableRelationshipsEquals(VehicleSubStatus expected, VehicleSubStatus actual) {}
}
