package br.com.supera.smartiot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VehicleManufacturerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleManufacturerAllPropertiesEquals(VehicleManufacturer expected, VehicleManufacturer actual) {
        assertVehicleManufacturerAutoGeneratedPropertiesEquals(expected, actual);
        assertVehicleManufacturerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleManufacturerAllUpdatablePropertiesEquals(VehicleManufacturer expected, VehicleManufacturer actual) {
        assertVehicleManufacturerUpdatableFieldsEquals(expected, actual);
        assertVehicleManufacturerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleManufacturerAutoGeneratedPropertiesEquals(VehicleManufacturer expected, VehicleManufacturer actual) {
        assertThat(expected)
            .as("Verify VehicleManufacturer auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleManufacturerUpdatableFieldsEquals(VehicleManufacturer expected, VehicleManufacturer actual) {
        assertThat(expected)
            .as("Verify VehicleManufacturer relevant properties")
            .satisfies(e -> assertThat(e.getManufacturerName()).as("check manufacturerName").isEqualTo(actual.getManufacturerName()))
            .satisfies(
                e -> assertThat(e.getManufacturerCountry()).as("check manufacturerCountry").isEqualTo(actual.getManufacturerCountry())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleManufacturerUpdatableRelationshipsEquals(VehicleManufacturer expected, VehicleManufacturer actual) {}
}
