package br.com.supera.smartiot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WaterSensorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaterSensorAllPropertiesEquals(WaterSensor expected, WaterSensor actual) {
        assertWaterSensorAutoGeneratedPropertiesEquals(expected, actual);
        assertWaterSensorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaterSensorAllUpdatablePropertiesEquals(WaterSensor expected, WaterSensor actual) {
        assertWaterSensorUpdatableFieldsEquals(expected, actual);
        assertWaterSensorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaterSensorAutoGeneratedPropertiesEquals(WaterSensor expected, WaterSensor actual) {
        assertThat(expected)
            .as("Verify WaterSensor auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaterSensorUpdatableFieldsEquals(WaterSensor expected, WaterSensor actual) {
        assertThat(expected)
            .as("Verify WaterSensor relevant properties")
            .satisfies(e -> assertThat(e.getSensorId()).as("check sensorId").isEqualTo(actual.getSensorId()))
            .satisfies(e -> assertThat(e.getSensorStatus()).as("check sensorStatus").isEqualTo(actual.getSensorStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaterSensorUpdatableRelationshipsEquals(WaterSensor expected, WaterSensor actual) {}
}
