name: Import JDL

on:
  push:
    paths:
      - 'app.jdl'
  workflow_dispatch:

jobs:
  import-jdl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install JHipster
      run: npm install -g generator-jhipster

    - name: Import JDL
      run: jhipster import-jdl app.jdl
      env:
        JHIPSTER_SKIP_CLIENT: true # Set to false if client generation is needed

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Import JDL'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
